# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b61fa2c6e5bf9940fc930d01203bfe44795bab3109ee500826bf2ced8140f59ecf7cc027f26a3ce2485ab37b31f2c1fc43b0e8ad07586097e935321f968fc55d

test:
  secret_key_base: 99b3ca53c31d8cf03d54c7c3fe791fe11d92de2828bf7a1cea6b82f657c1050121a6e1a36d7b48a1db245a2d2302b3530f1a50b428eea0d04d1ed3320fd1cc5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
